"""Filesystem and image asset helpers for UI end-to-end mock fixtures."""
from __future__ import annotations

from pathlib import Path
import shutil

from PIL import Image, ImageDraw

from prepare_lora_kit.pipeline import step_types
from prepare_lora_kit_ui.e2e.constants import (
    FIXTURE_MARKER,
    MOCK_DUPLICATE_NAME,
    MOCK_DUPLICATE_SOURCE,
    MOCK_PCA_EXTRA_COUNT,
    MOCK_UMAP_EXTRA_COUNT,
    MOCK_SOURCE_SPECS,
    MOCK_TOKEN,
)

_IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff", ".tif"}


def prepare_root(root: Path) -> None:
    marker = root / FIXTURE_MARKER
    if root.exists() and any(root.iterdir()) and not marker.exists():
        raise ValueError(
            f"Mock output root must be empty or previously generated by --mock: {root}"
        )
    root.mkdir(parents=True, exist_ok=True)
    marker.write_text("PrepareLoraKit UI mock fixture\n", encoding="utf-8")


def reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def write_source_images(
        input_dir: Path,
        *,
        include_pca_set: bool = False,
        include_umap_set: bool = False,
) -> None:
    for index, (name, size, color, _survives_quality) in enumerate(
            MOCK_SOURCE_SPECS,
            start=1,
    ):
        image = mock_image(size, color, f"PLK {index}")
        image.save(input_dir / name)

    shutil.copy2(input_dir / MOCK_DUPLICATE_SOURCE, input_dir / MOCK_DUPLICATE_NAME)

    if include_pca_set:
        for index in range(MOCK_PCA_EXTRA_COUNT):
            name = f"mock_pca_{index + 1:02d}.png"
            image = mock_dense_image(index, prefix="PCA")
            image.save(input_dir / name)

    if include_umap_set:
        for index in range(MOCK_UMAP_EXTRA_COUNT):
            name = f"mock_umap_{index + 1:02d}.png"
            image = mock_dense_image(index, prefix="UMAP")
            image.save(input_dir / name)


def mock_image(
        size: tuple[int, int],
        color: tuple[int, int, int],
        label: str,
) -> Image.Image:
    image = Image.new("RGB", size, color)
    draw = ImageDraw.Draw(image)
    width, height = size
    for offset in range(0, max(width, height), 96):
        shade = (
            min(color[0] + 35, 255),
            min(color[1] + 35, 255),
            min(color[2] + 35, 255),
        )
        draw.line((offset, 0, 0, offset), fill=shade, width=8)
    draw.rectangle((96, 96, width - 96, height - 96), outline=(235, 232, 216), width=12)
    draw.text((128, 128), label, fill=(255, 255, 255))
    return image


def mock_dense_image(index: int, *, prefix: str) -> Image.Image:
    width = 1280 + (index % 5) * 48
    height = 1280 + (index % 7) * 40
    color = (
        38 + (index * 37) % 180,
        52 + (index * 53) % 170,
        68 + (index * 71) % 160,
    )
    image = mock_image((width, height), color, f"{prefix} {index + 1}")
    draw = ImageDraw.Draw(image)
    x = 80 + (index * 97) % max(1, width - 360)
    y = 220 + (index * 131) % max(1, height - 520)
    accent = (
        255 - color[0] // 2,
        255 - color[1] // 2,
        255 - color[2] // 2,
    )
    draw.ellipse((x, y, x + 220, y + 180), outline=accent, width=18)
    draw.rectangle(
        (
            width - 420 - (index % 4) * 32,
            280 + (index % 6) * 48,
            width - 120,
            580 + (index % 6) * 48,
        ),
        outline=accent,
        width=16,
    )
    return image


def seed_working_dataset(
        input_dir: Path,
        working_dir: Path,
        selected_steps: list[str],
) -> None:
    if "ImportStep" in selected_steps:
        return
    working_dir.mkdir(parents=True, exist_ok=True)
    ordered_steps = list(step_types())
    first_index = min(ordered_steps.index(step) for step in selected_steps)
    quality_index = ordered_steps.index("QualityGateStep")
    names = (
        quality_survivor_names(input_dir)
        if first_index > quality_index
        else source_image_names(input_dir)
    )
    for name in names:
        shutil.copy2(input_dir / name, working_dir / name)


def source_image_names(input_dir: Path | None = None) -> list[str]:
    names = [name for name, _size, _color, _survives_quality in MOCK_SOURCE_SPECS] + [
        MOCK_DUPLICATE_NAME
    ]
    if input_dir is not None:
        names.extend(sorted(path.name for path in input_dir.glob("mock_pca_*.png")))
        names.extend(sorted(path.name for path in input_dir.glob("mock_umap_*.png")))
    return names


def quality_survivor_names(input_dir: Path | None = None) -> list[str]:
    names = [
        name
        for name, _size, _color, survives_quality in MOCK_SOURCE_SPECS
        if survives_quality
    ]
    names.append(MOCK_DUPLICATE_NAME)
    if input_dir is not None:
        names.extend(sorted(path.name for path in input_dir.glob("mock_pca_*.png")))
        names.extend(sorted(path.name for path in input_dir.glob("mock_umap_*.png")))
    return names


def write_captions(working_dir: Path) -> None:
    for image_path in sorted(working_dir.iterdir()):
        if image_path.suffix.lower() in _IMAGE_SUFFIXES:
            image_path.with_suffix(".txt").write_text(
                f"{MOCK_TOKEN}, deterministic mock caption for {image_path.stem}.",
                encoding="utf-8",
            )
