"""Filesystem and image asset helpers for UI end-to-end mock fixtures."""
from __future__ import annotations

from pathlib import Path
import shutil

from PIL import Image, ImageDraw

from ...project.base import STEP_TYPE_MAP
from .constants import (
    FIXTURE_MARKER,
    MOCK_DUPLICATE_NAME,
    MOCK_DUPLICATE_SOURCE,
    MOCK_SOURCE_SPECS,
    MOCK_TOKEN,
)


_IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff", ".tif"}


def prepare_root(root: Path) -> None:
    marker = root / FIXTURE_MARKER
    if root.exists() and any(root.iterdir()) and not marker.exists():
        raise ValueError(
            f"Mock output root must be empty or previously generated by --mock: {root}"
        )
    root.mkdir(parents=True, exist_ok=True)
    marker.write_text("PrepareLoraKit UI mock fixture\n", encoding="utf-8")


def reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def write_source_images(input_dir: Path) -> None:
    for index, (name, size, color, _survives_quality) in enumerate(
        MOCK_SOURCE_SPECS,
        start=1,
    ):
        image = mock_image(size, color, f"PLK {index}")
        image.save(input_dir / name)

    shutil.copy2(input_dir / MOCK_DUPLICATE_SOURCE, input_dir / MOCK_DUPLICATE_NAME)


def mock_image(
    size: tuple[int, int],
    color: tuple[int, int, int],
    label: str,
) -> Image.Image:
    image = Image.new("RGB", size, color)
    draw = ImageDraw.Draw(image)
    width, height = size
    for offset in range(0, max(width, height), 96):
        shade = (
            min(color[0] + 35, 255),
            min(color[1] + 35, 255),
            min(color[2] + 35, 255),
        )
        draw.line((offset, 0, 0, offset), fill=shade, width=8)
    draw.rectangle((96, 96, width - 96, height - 96), outline=(235, 232, 216), width=12)
    draw.text((128, 128), label, fill=(255, 255, 255))
    return image


def seed_working_dataset(
    input_dir: Path,
    working_dir: Path,
    selected_steps: list[str],
) -> None:
    working_dir.mkdir(parents=True, exist_ok=True)
    first_index = min(list(STEP_TYPE_MAP).index(step) for step in selected_steps)
    quality_index = list(STEP_TYPE_MAP).index("QualityGateStep")
    names = (
        quality_survivor_names()
        if first_index > quality_index
        else source_image_names()
    )
    for name in names:
        shutil.copy2(input_dir / name, working_dir / name)


def source_image_names() -> list[str]:
    return [name for name, _size, _color, _survives_quality in MOCK_SOURCE_SPECS] + [
        MOCK_DUPLICATE_NAME
    ]


def quality_survivor_names() -> list[str]:
    names = [
        name
        for name, _size, _color, survives_quality in MOCK_SOURCE_SPECS
        if survives_quality
    ]
    names.append(MOCK_DUPLICATE_NAME)
    return names


def write_captions(working_dir: Path) -> None:
    for image_path in sorted(working_dir.iterdir()):
        if image_path.suffix.lower() in _IMAGE_SUFFIXES:
            image_path.with_suffix(".txt").write_text(
                f"{MOCK_TOKEN}, deterministic mock caption for {image_path.stem}.",
                encoding="utf-8",
            )
