"""Developer-only mock fixture support for UI step smoke runs."""
from __future__ import annotations

from dataclasses import dataclass
import shutil
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw

from ..paths import PROJECT_ROOT
from ..project.base import ProjectConfig, PipelineStep, STEP_TYPE_MAP
from ..project.configs import (
    AuditConfig,
    BucketDryRunConfig,
    CaptionConfig,
    ConfigGenConfig,
    DedupeConfig,
    QualityGateConfig,
    ScorerEntry,
    UpscaleConfig,
    VaeGateConfig,
)
from ..utils.state import RunState


MOCK_PROJECT_NAME = "plk-ui-mock"
MOCK_TOKEN = "plk_mock"
_FIXTURE_MARKER = ".plk_ui_mock_fixture"


@dataclass(frozen=True)
class MockUiFixture:
    root: Path
    input_dir: Path
    output_dir: Path
    project: ProjectConfig
    selected_steps: list[str]
    token: str = MOCK_TOKEN

    def bootstrap_payload(self) -> dict[str, Any]:
        return {
            "project": self.project.name,
            "input_dir": str(self.input_dir),
            "output_dir": str(self.output_dir),
            "selected_steps": list(self.selected_steps),
            "force": True,
            "token": self.token,
            "mock_runtime": True,
        }


_STEP_ALIASES: dict[str, str] = {}
for _index, _step_type in enumerate(STEP_TYPE_MAP, start=1):
    _STEP_ALIASES[str(_index)] = _step_type
    _STEP_ALIASES[f"s{_index}"] = _step_type


def resolve_mock_steps(raw: str) -> list[str]:
    value = raw.strip()
    if not value:
        raise ValueError("Mock step cannot be empty")
    if value.lower() == "all":
        return list(STEP_TYPE_MAP)

    lowered = value.lower()
    if lowered in _STEP_ALIASES:
        return [_STEP_ALIASES[lowered]]
    for step_type in STEP_TYPE_MAP:
        if step_type.lower() == lowered:
            return [step_type]

    known = ", ".join(["all", *STEP_TYPE_MAP, *[f"s{i}" for i in range(1, len(STEP_TYPE_MAP) + 1)]])
    raise ValueError(f"Unknown mock step '{raw}'. Known: {known}")


def create_mock_ui_fixture(raw_step: str, root: Path | None = None) -> MockUiFixture:
    selected_steps = resolve_mock_steps(raw_step)
    root = (root or PROJECT_ROOT / "outputs" / "_ui_mock").expanduser().resolve()
    _prepare_root(root)
    input_dir = root / "input"
    output_dir = root / "run"
    working_dir = output_dir / "dataset"

    _reset_dir(input_dir)
    _reset_dir(output_dir)
    _write_source_images(input_dir)
    _seed_working_dataset(input_dir, working_dir)

    project = _mock_project(input_dir)
    _seed_state(output_dir, selected_steps)
    if _needs_seeded_captions(selected_steps):
        _write_captions(working_dir)

    return MockUiFixture(
        root=root,
        input_dir=input_dir,
        output_dir=output_dir,
        project=project,
        selected_steps=selected_steps,
    )


def _prepare_root(root: Path) -> None:
    marker = root / _FIXTURE_MARKER
    if root.exists() and any(root.iterdir()) and not marker.exists():
        raise ValueError(
            f"Mock output root must be empty or previously generated by --mock: {root}"
        )
    root.mkdir(parents=True, exist_ok=True)
    marker.write_text("PrepareLoraKit UI mock fixture\n", encoding="utf-8")


def _reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _write_source_images(input_dir: Path) -> None:
    specs = [
        ("mock_square.png", (1536, 1536), (46, 88, 138)),
        ("mock_landscape.png", (1792, 1536), (121, 78, 55)),
        ("mock_portrait.png", (1536, 1792), (65, 112, 82)),
    ]
    for index, (name, size, color) in enumerate(specs, start=1):
        image = _mock_image(size, color, f"PLK {index}")
        image.save(input_dir / name)

    shutil.copy2(input_dir / "mock_square.png", input_dir / "mock_square_duplicate.png")


def _mock_image(size: tuple[int, int], color: tuple[int, int, int], label: str) -> Image.Image:
    image = Image.new("RGB", size, color)
    draw = ImageDraw.Draw(image)
    width, height = size
    for offset in range(0, max(width, height), 96):
        shade = (
            min(color[0] + 35, 255),
            min(color[1] + 35, 255),
            min(color[2] + 35, 255),
        )
        draw.line((offset, 0, 0, offset), fill=shade, width=8)
    draw.rectangle((96, 96, width - 96, height - 96), outline=(235, 232, 216), width=12)
    draw.text((128, 128), label, fill=(255, 255, 255))
    return image


def _seed_working_dataset(input_dir: Path, working_dir: Path) -> None:
    working_dir.mkdir(parents=True, exist_ok=True)
    for image_path in sorted(input_dir.iterdir()):
        if image_path.is_file():
            shutil.copy2(image_path, working_dir / image_path.name)


def _write_captions(working_dir: Path) -> None:
    for image_path in sorted(working_dir.iterdir()):
        if image_path.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff", ".tif"}:
            image_path.with_suffix(".txt").write_text(
                f"{MOCK_TOKEN}, deterministic mock caption for {image_path.stem}.",
                encoding="utf-8",
            )


def _seed_state(output_dir: Path, selected_steps: list[str]) -> None:
    first_index = min(list(STEP_TYPE_MAP).index(step) for step in selected_steps)
    state = RunState(output_dir)
    for step_type in list(STEP_TYPE_MAP)[:first_index]:
        state.mark_done(step_type, {"mock_fixture": True})


def _needs_seeded_captions(selected_steps: list[str]) -> bool:
    first_index = min(list(STEP_TYPE_MAP).index(step) for step in selected_steps)
    caption_index = list(STEP_TYPE_MAP).index("CaptionStep")
    return first_index > caption_index


def _mock_project(input_dir: Path) -> ProjectConfig:
    return ProjectConfig(
        name=MOCK_PROJECT_NAME,
        network="flux-klein-9b",
        input_dir=str(input_dir),
        pipeline=[
            PipelineStep(
                "QualityGateStep",
                QualityGateConfig(
                    scorers=[ScorerEntry(name="min_side", op="lt", threshold=512.0)],
                    auto_only=True,
                ),
            ),
            PipelineStep("DedupeStep", DedupeConfig(skip_clip=True)),
            PipelineStep(
                "UpscaleStep",
                UpscaleConfig(upscale_target=1664, upscale_model="lanczos"),
            ),
            PipelineStep("VaeGateStep", VaeGateConfig()),
            PipelineStep(
                "CaptionStep",
                CaptionConfig(
                    qwen_model_id="mock",
                    vram_tier="auto",
                    max_new_tokens=32,
                    spot_check_pct=0.0,
                ),
            ),
            PipelineStep("AuditStep", AuditConfig()),
            PipelineStep("ConfigGenStep", ConfigGenConfig()),
            PipelineStep("BucketDryRunStep", BucketDryRunConfig()),
        ],
    )
